### ISSUE TITLE
Cobros por cancelación

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#11]
La forma en que trabaja el cliente ahora mismo es:

-Si el cliente anula la reserva 24 horas antes de la fecha, se le cobran 10 euros (aunque muchas veces no se hace).
-Si el cliente anula la reserva en el día, se le cobra la reserva (aunque a veces tampoco se hace).

Se tiene que poder modificar la factura de una reserva cancelada para cobrarle la cifra que queramos.

**Comment by PaulJBis** [comment]
Preguntado en foro.

**Comment by sirym** [comment]
Por el momento ya se actualiza la factura con el cobro de las cantidades marcadas, solo falta que el tpv esté online para terminar la parte de enviarlo al tpv para cobrarlo

**Comment by PaulJBis** [comment]
Hecho, por lo que parece. OJO: a notar: cuando se cancela una reserva, hay que cancelarla y después, marcar la factura como cobrada para que cobre en el TPV.
