### ISSUE TITLE
Modificar fecha de reserva: ¿se puede hacer más fácil?

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#12]
Ahora mismo, para modificar la fecha de una reserva, hay que entrar a "Modificar reserva" y pasar por todo el UI de "Añadir reserva". ¿Hay alguna forma más rápida de hacerlo?

**Comment by sirym** [comment]
Se puede arrastrar una reserva de un día a otro en el calendario
