### ISSUE TITLE
Numeración de facturas: ¿se puede mejorar?

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#13]
Ver si se puede mejorar la numeración de las facturas, para que sea 01-2017, 02-2017, etc.

**Comment by sirym** [comment]
deberia reiniciarse la numeracion cuando cambie de año?

**Comment by PaulJBis** [comment]
Sí. Se reinicia la numeración con el año.

**Comment by sirym** [comment]
hecho

**Comment by PaulJBis** [comment]
Solo una cosa: cuando lo pasemos a producción, ¿cómo se resetea el nº de facturas para comenzar desde cero?

**Comment by sirym** [comment]
simplemente vaciando la tabla 'zg8s1_jomres_numeracion_facturas'
