### ISSUE TITLE
Redirigir a página de admin tras hacer login

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#15]
Tras hacer login como administrador, el sistema debería redirigirnos al Panel de Control del hotel.

**Comment by PaulJBis** [comment]
Rectifico: se puede hacer login en Jomres y entrar en el panel de control de Jomres sin entrar en Joomla. Antes no podía porque no tenía la URL exacta.

**Comment by sirym** [comment]
Ya está hecho con este plugin https://extensions.joomla.org/extension/redirect-on-login

**Comment by sirym** [comment]
Si hace falta monto una página de login y quito del menú la opcion, es bastante sencillo

**Comment by sirym** [comment]
http://gestion.hoteljacobeo.net/index.php?option=com_users&view=login
