### ISSUE TITLE
Poder elegir qué habitación concreta dar a cada cliente.

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#2]
En las reservas rápidas, se puede elegir qué habitación dar a cada cliente. Pero, ¿se puede hacer en las reservas "normales"?

Importante, porque las reservas en grupo sólo se pueden hacer en "Nueva reserva".

**Comment by PaulJBis** [comment]
Es posible que se pueda configurar esto en la página de "Settings", para que en la página de reservas salgan las habitaciones una a una, en vez de simplemente el nº de habitaciones. Comprobar.

**Comment by sirym** [comment]
Ahora mismo está listando todas las habitaciones y cuando le damos a "Haga click para más información..." aparece el número de habitación entre otros detalles

**Comment by PaulJBis** [comment]
¿No hay forma de que salga el nº de habitación en la misma lista, sin tener que hacer click?

**Comment by sirym** [comment]
He desactivado lo de "más información", porque era redundante y he puesto el número de habitación sin hacer click.

**Comment by sirym** [comment]
Añadido tambien como opciones visibles el número de habitacion, planta y nombre (ya lo editamos según sea en el hotel)

**Comment by PaulJBis** [comment]
Lo ideal sería que:
-En la Web pública el cliente no debería poder seleccionar la habitación.
-En la Web de admin. sí se debería poder.

**Comment by PaulJBis** [comment]
Preguntado a soporte:

> in dobooking.class.php line 359 where you have:
> 
>```
 if (!isset($mrConfig[ 'booking_form_rooms_list_style' ])) {
 $mrConfig[ 'booking_form_rooms_list_style' ] = '1';
 }
```
> 
> below add:
> 
> ```
$thisJRUser = jomres_getSingleton('jr_user');
 if ($thisJRUser->userIsManager) {
 $mrConfig[ 'booking_form_rooms_list_style' ] = '1';
 }
```
> 
> I haven`t tested this but it should work..

**Comment by PaulJBis** [comment]
De todas formas, vamos a dejar esto en stand-by hasta que el cliente lo vea. Igual le vale con  seleccionar simplemente por habitaciones de 1 cama o 2.

De momento, vamos a configurar el sistema para que muestre sólo tipos de habitación, tanto en público como en privado.

**Comment by PaulJBis** [comment]
Al editar una reserva, sale la lista entera de todas las habitaciones. Esto es así también en el Jomres original.
