### ISSUE TITLE
Añadir texto con "forma de pago" a cada reserva en la pag. de admin.

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#23]
En la vista de admin., hay que añadir un texto con la forma de pago de cada reserva en los datos de ésta.

**Comment by sirym** [comment]
Corregido, ha hecho falta editar el archivo 'edit_booking_tabcontents_payment.html' que está fuera del git

**Comment by PaulJBis** [comment]
¿De dónde saca ese dato? Si editamos una reserva, no lo vuelve a rellenar, ¿no?

**Comment by sirym** [comment]
Hay una tabla en la base de datos, que es para esto. zg8s1_jomres_invoice_payment_ref y que hasta ahora no utilizábamos. Ahí se indica el número de factura, el gateway y si está pagado o no.
Si se edita la reserva, como el número de factura es el mismo, sigue siendo el mismo método de pago, no se pierde esta información.
