### ISSUE TITLE
Más facilidad al modificar los datos de una reserva

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#34]
Para modificar los datos de una reserva, ahora hay que volver a pasar todo el proceso de seleccionar habitación, comprobar datos... Buscar una nueva forma que sea más ágil.

Los datos de una reserva son:
-[X] Datos del cliente.
-[X] Precio.
-Fecha.
-Habitaciones seleccionadas.

De todos estos datos, los únicos que requieren pasar por el proceso completo son los de "hab. seleccionadas". Los demás se podrían modificar con nuevos formularios en la página de la reserva.

Idea: junto a los datos del cliente, añadir simplemente un enlace a la página de "Editar cliente".
Añadir también una pestaña para modificar precio.

**Comment by PaulJBis** [comment]
Se ha añadido el enlace para "Editar datos de cliente".

**Comment by PaulJBis** [comment]
"Editar datos de cliente": ahora, al guardar los datos, vuelve a la factura, en vez de a la lista de clientes.

**Comment by PaulJBis** [comment]
Respecto a los precios, depende de cómo quiera el cliente configurar precios: ¿por cliente?, etc.

**Comment by PaulJBis** [comment]
El formulario de override guardar el precio usando una consulta jQuery: 

<a href="javascript:void(0);" onclick="getResponse_override('override',jomresJquery('#override_room_total').val()+'^'+jomresJquery('#override_deposit').val())" class="btn btn-default">Guardar precio personalizado</a>

http://jomres.hoteljacobeo.net/index.php?option=com_jomres&no_html=1&jrajax=1&Itemid=234&lang=es&tmpl=jomres&task=handlereq&property_uid_check=2&field=override&value=40%5E&_=1486928076143

**Comment by PaulJBis** [comment]
La plantilla de la pestaña "Pago", en "Modificar reserva": edit_booking_tabcontents_payment. Se trataría de añadir el formulario, con sus jQuery y demás, allí.

**Comment by PaulJBis** [comment]
Funciones que habría que añadir a la página nueva:

-property_uid_check: parte de la validación Jquery que usa dobooking.html en los formularios.
-	`<input type="hidden" id="booking_form_property_uid" name="property_uid" value="{PROPERTYUID}">`: campo oculto.

**Comment by albertomerino** [comment]
Esto ya está.

**Comment by PaulJBis** [comment]
Técnicamente, quedaría aún poner un calendario para modificar la fecha fácilmente, pero pensándolo bien, no estoy seguro de que sea buena idea: el admin. podría elegir otra fecha en la que no quedaran habitaciones. Sería mejor en ese caso obligarle a que pase por el proceso de modificación completo. Por tanto, cerramos este bug.
