### ISSUE TITLE
Clientes: quitar datos obligatorios

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#4]
Hacer que el único dato obligatorio al dar de alta a un cliente en admin. sea el teléfono.

**Comment by sirym** [comment]
Este ya lo solucioné, se me olvidó marcarlo

**Comment by PaulJBis** [comment]
Acabo de probar a hacer una reserva en modo admin., sin poner el nombre del cliente, y no me deja. No funciona ni en modo de reserva rápida, ni en el normal.

**Comment by PaulJBis** [comment]
Corrijo: el nombre del cliente sigue siendo obligatorio, pero los demás campos (excepto el teléfono) no lo son.

**Comment by PaulJBis** [comment]
En "Reserva rápida", me pide la dirección de email. Sin ella no puedo hacer la reserva.

**Comment by sirym** [comment]
Ok, no me di cuenta de lo del nombre. Estaba como obligatorio. Lo de reserva rápida lo tengo que revisar

**Comment by sirym** [comment]
En reserva rápida los datos son obligatorios si o si, no hay forma de permitir campos vacios sin editar archivos de core

**Comment by sirym** [comment]
Tampoco me deja seleccionar método de pago en este modo, creo que lo suyo es desactivarlo o decirle al cliente las limitaciones que tiene este método

**Comment by PaulJBis** [comment]
Al final, la validación se hace en jomres_generic_insert_booking.class.php, así que se puede editar esa función.

A revisar: ¿cómo hace las reservas entonces desde la Web pública, si en ella se puede hacer que haya campos no obligatorios?

**Comment by PaulJBis** [comment]
En la Web pública, al hacer una reserva activa el evento 02990. La clase j02990showconfirmation.class.php tiene comentada la parte que comprueba los campos. ¿Lo hizo Alberto?

**Comment by PaulJBis** [comment]
Página pública:
-Todos los datos deben ser obligatorios.

Página privada:
-El único dato obligatorio debe ser el teléfono.

**Comment by PaulJBis** [comment]
Hecho. El único problema: en "Reservas Rápidas", siempre da el error de que no hay nº de móvil, incluso cuando lo hay. Comprobar.

**Comment by PaulJBis** [comment]
En el caso "Editar reserva", no parece que haya problemas.
