### ISSUE TITLE
Facturas: maquetar correctamente

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#7]
Las facturas de papel deberían estar mejor maquetadas, en vertical en vez de en horizontal, como están ahora.

**Comment by sirym** [comment]
Al imprimir se ajusta el formato a vertical para tamaño A4 y queda perfectamente

**Comment by sirym** [comment]
A esto le falta algo?

**Comment by PaulJBis** [comment]
A consultar con el cliente. Yo lo veo bien, pero creo recordar que se quejaba de que, cuando estaba en vertical, la cabecera quedaba fea: los recuadros de los datos de cliente, etc., eran demasiado estrechos.

**Comment by PaulJBis** [comment]
Visto. Los recuadros para los datos del cliente y del hotel son demasiado pequeños; se salen los datos.

**Comment by sirym** [comment]
Hecho
