### ISSUE TITLE
Depósitos y formas de cobro

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Hotel-Jomres#9]
La forma actual de trabajar es:

-Clientes particulares: no se les cobra depósito, pero se les pide una tarjeta de crédito.
-Empresas: no se les pide tarjeta.

Programar el sistema para resolver estos dos sistemas, teniendo en cuenta también los requerimientos de seguridad de tener que guardar nº de tarjeta.

**Comment by PaulJBis** [comment]
Sobre Jomres y guardar tarjetas de crédito:

https://www.jomres.net/forum/General-discussion/11827-no-show-risk-store-credit-card-details?limitstart=0#11982

https://www.jomres.net/forum/How-do-I/24919-credit-card-detail-at-booking-time#42049

**Comment by PaulJBis** [comment]
Me dicen en el foro que se puede modificar el código para esto.

**Comment by PaulJBis** [comment]
El TPV de CECA soporta tokenización, pero no permite que pidamos nosotros el nº de tarjeta.

**Comment by sirym** [comment]
Ahora mismo está configurado para que se cobre un pequeño depósito de 0,01€ para activar la tokenizacion (me parece una chapuza por parte de ceca, en pago como stripe no necesita ninguna señal, solo se indica cual será la cantidad a cobrar en tal fecha)

**Comment by PaulJBis** [comment]
Bien, pero si luego el cliente no se presenta, ¿puede el administrador forzar a cobrar la reserva entera? ¿O meter una cantidad arbitraria? (1o euros, por ejemplo).

**Comment by sirym** [comment]
para poder pasar al tpv siendo administrador es necesario modificar el case 'confirmbooking' de jomres/jomres.php y forzar para todos los usuarios igual

**Comment by sirym** [comment]
¿Este se puede cerrar, no? ¿O falta algo?

**Comment by PaulJBis** [comment]
Lo estoy probando.

**Comment by PaulJBis** [comment]
Ahora mismo, las reservas con tokenización no se están cobrando. El TPV no las cobra (y no marca la introducción inicial de tarjeta como tokenizada tampoco).

**Comment by PaulJBis** [comment]
Arreglado. A notar: cuando se cancela una reserva, hay que cancelarla y *después*, marcar la factura como cobrada para que cobre en el TPV.
